import { ScheduleSystemType, SystemConfig } from '../types';

export const SYSTEM_CONFIGS: Record<ScheduleSystemType, SystemConfig> = {
  'standard': {
    name: '一般工時',
    type: 'standard',
    cycleDays: 7,
    maxConsecutiveWorkDays: 6,
    minMandatoryOffPerCycle: 1,
    minRestDaysPerCycle: 1,
    maxNormalHoursPerCycle: 40,
    maxDailyNormalHours: 8,
    description: '每7日中應有1日例假日、1日休息日。每日正常工時不得超過8小時，每週不得超過40小時。不得連續工作超過6天。',
    legalBasis: '勞基法第30條第1項、第36條第1項',
    applicableIndustries: '所有未特別申請變形工時之一般行業',
  },
  '2-week': {
    name: '2週變形工時',
    type: '2-week',
    cycleDays: 14,
    maxConsecutiveWorkDays: 6,
    minMandatoryOffPerCycle: 2,
    minRestDaysPerCycle: 2,
    maxNormalHoursPerCycle: 80,
    maxDailyNormalHours: 10,
    description: '每2週內，得將2日之正常工作時數分配於其他工作日，每日正常工時至多10小時。每2週應有2日例假及2日休息日。每7日中至少有1日例假，不得連續工作超過6天。',
    legalBasis: '勞基法第30條第2項',
    applicableIndustries: '適用勞基法之所有行業 (如加油站、批發零售、一般製造等)',
  },
  '4-week': {
    name: '4週變形工時',
    type: '4-week',
    cycleDays: 28,
    maxConsecutiveWorkDays: 12,
    minMandatoryOffPerCycle: 4,
    minRestDaysPerCycle: 4,
    maxNormalHoursPerCycle: 160,
    maxDailyNormalHours: 10,
    description: '每4週內正常工作總時數不得超過160小時。每日正常工時至多10小時。每2週內至少應有2日例假，每4週內之例假及休息日至少應有8日。經彈性排班最多可連續工作12天。',
    legalBasis: '勞基法第30條之1',
    applicableIndustries: '中央主管機關指定行業：餐飲業、觀光飯店、銀行業、娛樂業、醫療保健業、加油站業等',
  },
  '8-week': {
    name: '8週變形工時',
    type: '8-week',
    cycleDays: 56,
    maxConsecutiveWorkDays: 6,
    minMandatoryOffPerCycle: 8,
    minRestDaysPerCycle: 8,
    maxNormalHoursPerCycle: 320,
    maxDailyNormalHours: 8,
    description: '每8週內正常工作總時數不得超過320小時。每日正常工時仍不得超過8小時。每8週內應有8日例假及8日休息日。每7日中至少有1日例假，不得連續工作超過6天。',
    legalBasis: '勞基法第30條第3項',
    applicableIndustries: '中央主管機關指定行業：製造業、大眾運輸業、營造業、郵政業等',
  },
};
